








'use strict';

const crypto = require('crypto');

// Mock dependencies
jest.mock('jsonwebtoken', () => ({
    sign: jest.fn(() => 'signed_access_token'),
    verify: jest.fn(),
}));

jest.mock('bcryptjs', () => ({
    compare: jest.fn(),
    genSalt: jest.fn(() => 'salt'),
    hash: jest.fn(() => 'hashed_pw'),
}));

jest.mock('mongoose', () => ({
    Types: {
        ObjectId: jest.fn((id) => id),
    },
}));

jest.mock('@urbackend/common', () => {
    const z = require('zod');
    const mockModel = {
        findOne: jest.fn().mockReturnThis(),
        create: jest.fn(),
        updateOne: jest.fn(),
        select: jest.fn().mockReturnThis(),
        lean: jest.fn().mockReturnThis(),
    };

    const projectFindByIdChain = {
        select: jest.fn().mockReturnThis(),
        lean: jest.fn(),
    };

    return {
        Project: {
            findById: jest.fn(() => projectFindByIdChain),
            __chain: projectFindByIdChain,
        },
        redis: {
            set: jest.fn().mockResolvedValue('OK'),
            get: jest.fn(),
            del: jest.fn().mockResolvedValue(1),
            incr: jest.fn().mockResolvedValue(1),
            expire: jest.fn().mockResolvedValue(1),
            ttl: jest.fn().mockResolvedValue(-1),
        },
        authEmailQueue: { add: jest.fn().mockResolvedValue(undefined) },
        loginSchema: z.object({
            email: z.string().email(),
            password: z.string().min(1),
        }),
        userSignupSchema: z.object({
            email: z.string().email(),
            password: z.string().min(6),
        }).passthrough(),
        resetPasswordSchema: z.object({
            email: z.string().email(),
            otp: z.string(),
            newPassword: z.string().min(6),
        }),
        onlyEmailSchema: z.object({ email: z.string().email() }),
        verifyOtpSchema: z.object({ email: z.string().email(), otp: z.string() }),
        changePasswordSchema: z.object({
            currentPassword: z.string().min(1),
            newPassword: z.string().min(6),
        }),
        sanitize: jest.fn((data) => data),
        getConnection: jest.fn().mockResolvedValue({}),
        getCompiledModel: jest.fn(() => mockModel),
        __mockModel: mockModel,
        // Mock refreshToken logic
        getRefreshSession: jest.fn(),
        persistRefreshSession: jest.fn().mockResolvedValue(undefined),
        revokeSessionChain: jest.fn().mockResolvedValue(undefined),
        AppError: class AppError extends Error { constructor(statusCode, message) { super(message); this.statusCode = statusCode; } },
        ApiResponse: class ApiResponse { constructor(d, m) { this.data=d; this.message=m; this.success=true; } send(res, code) { return res.status(code).json({ success: this.success, data: this.data, message: this.message }); } },
        checkLockout: jest.fn().mockResolvedValue({ locked: false, retryAfterSeconds: 0 }),
        recordFailedAttempt: jest.fn().mockResolvedValue({ locked: false, retryAfterSeconds: 0, attempts: 1 }),
        clearLockout: jest.fn().mockResolvedValue(undefined),
    };
});

jest.mock('../utils/refreshToken', () => ({
    issueAuthTokens: jest.fn().mockResolvedValue({
        accessToken: 'signed_access_token',
        refreshToken: 'refresh_token_123',
        expiresIn: '15m'
    }),
    shouldExposeRefreshToken: jest.fn(() => true),
}));

const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { AppError, redis, authEmailQueue, __mockModel: mockModel, checkLockout, recordFailedAttempt, clearLockout } = require('@urbackend/common');
const { issueAuthTokens } = require('../utils/refreshToken');
const controller = require('../controllers/userAuth.controller');

const makeProject = (overrides = {}) => ({
    _id: 'project_1',
    name: 'Demo',
    jwtSecret: 'jwt_secret',
    isAuthEnabled: true,
    resources: { db: { isExternal: false } },
    collections: [{ 
        name: 'users', 
        model: [
            { key: 'email', type: 'String', required: true }, 
            { key: 'password', type: 'String', required: true },
            { key: 'isVerified', type: 'Boolean' }
        ] 
    }],
    ...overrides
});

const makeReq = ({ body = {}, headers = {}, project = makeProject() } = {}) => ({
    body,
    project,
    headers,
    header: jest.fn((key) => headers[key] || headers[key?.toLowerCase()] || null),
});

const makeRes = () => {
    const res = {
        status: jest.fn(),
        json: jest.fn(),
    };
    res.status.mockReturnValue(res);
    res.json.mockReturnValue(res);
    return res;
};

describe('OTP generation uses CSPRNG', () => {
    let randomIntSpy;

    let next;
beforeEach(() => {
next = jest.fn();
        jest.clearAllMocks();
        randomIntSpy = jest.spyOn(crypto, 'randomInt');
    });

    afterEach(() => {
        randomIntSpy.mockRestore();
    });

    test('signup queues OTP generated by crypto.randomInt', async () => {
        const req = makeReq({ body: { email: 'new@user.com', password: 'password123' } });
        const res = makeRes();
        const { __mockModel: model } = require('@urbackend/common');
        model.findOne.mockResolvedValueOnce(null);
        model.create.mockResolvedValueOnce({ _id: 'u1' });

        await controller.signup(req, res, next);

        expect(randomIntSpy).toHaveBeenCalledWith(100000, 1000000);
        const storedOtp = require('@urbackend/common').redis.set.mock.calls.find(
            c => c[0].includes('otp:verification')
        )?.[1];
        expect(storedOtp).toMatch(/^\d{6}$/);
    });

    test('signup unverified-resend branch uses crypto.randomInt', async () => {
        const req = makeReq({ body: { email: 'Unverified@User.com', password: 'password123' } });
        const res = makeRes();
        const { __mockModel: model, redis } = require('@urbackend/common');
        model.findOne.mockResolvedValueOnce({ _id: 'u1', isVerified: false });
        redis.get.mockResolvedValueOnce(null);

        await controller.signup(req, res, next);

        expect(randomIntSpy).toHaveBeenCalledWith(100000, 1000000);
        const otpCall = redis.set.mock.calls.find(c => c[0].includes('otp:verification'));
        expect(otpCall[0]).toContain('unverified@user.com');
    });

    test('resendVerificationOtp uses crypto.randomInt', async () => {
        const req = makeReq({ body: { email: 'unverified@user.com' } });
        const res = makeRes();
        const { __mockModel: model, redis } = require('@urbackend/common');
        model.findOne.mockResolvedValueOnce({ _id: 'u1', isVerified: false });
        redis.get.mockResolvedValueOnce(null);

        await controller.resendVerificationOtp(req, res, next);

        expect(randomIntSpy).toHaveBeenCalledWith(100000, 1000000);
    });

    test('requestPasswordReset uses crypto.randomInt', async () => {
        const req = makeReq({ body: { email: 'reset@user.com' } });
        const res = makeRes();
        require('@urbackend/common').__mockModel.findOne.mockResolvedValueOnce({ _id: 'u1' });

        await controller.requestPasswordReset(req, res, next);

        expect(randomIntSpy).toHaveBeenCalledWith(100000, 1000000);
    });
});

describe('Email Authentication Flow', () => {
    let next;
beforeEach(() => {
next = jest.fn();
        jest.clearAllMocks();
    });

    describe('signup', () => {
        test('successfully creates user and queues verification email', async () => {
            const req = makeReq({
                body: { email: 'new@user.com', password: 'password123' }
            });
            const res = makeRes();

            mockModel.findOne.mockResolvedValueOnce(null); // User does not exist
            mockModel.create.mockResolvedValueOnce({ _id: 'user_123' });

            await controller.signup(req, res, next);

            expect(mockModel.findOne).toHaveBeenCalled();
            expect(mockModel.create).toHaveBeenCalledWith(expect.objectContaining({
                email: 'new@user.com',
                password: 'hashed_pw',
                isVerified: false
            }));
            
            expect(redis.set).toHaveBeenCalledWith(
                expect.stringContaining('otp:verification:new@user.com'),
                expect.any(String),
                'EX',
                300
            );

            expect(authEmailQueue.add).toHaveBeenCalledWith('send-verification-email', expect.objectContaining({
                email: 'new@user.com',
                type: 'verification'
            }));

            expect(clearLockout).toHaveBeenCalledWith('project_1', 'new@user.com');

            expect(issueAuthTokens).toHaveBeenCalled();
            
            expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({
                token: 'signed_access_token',
                userId: 'user_123'
            })
    );
        });

        test('returns 400 if user already exists', async () => {
            const req = makeReq({
                body: { email: 'existing@user.com', password: 'password123' }
            });
            const res = makeRes();

            mockModel.findOne.mockResolvedValueOnce({ _id: 'user_123', email: 'existing@user.com', isVerified: true });

            await controller.signup(req, res, next);

            expect(next).toHaveBeenCalledWith(expect.any(AppError));
            expect(next.mock.calls[next.mock.calls.length - 1][0].statusCode).toBe(400);
            
        });
        
        test('resends verification if user exists but unverified', async () => {
            const req = makeReq({
                body: { email: 'unverified@user.com', password: 'password123' }
            });
            const res = makeRes();

            mockModel.findOne.mockResolvedValueOnce({ _id: 'user_123', email: 'unverified@user.com', isVerified: false });
            redis.get.mockResolvedValueOnce(null); // No cooldown

            await controller.signup(req, res, next);

            expect(mockModel.create).not.toHaveBeenCalled();
            expect(authEmailQueue.add).toHaveBeenCalled();
            
        });
    });

    describe('verifyEmail', () => {
        test('verifies email with valid OTP', async () => {
            const req = makeReq({
                body: { email: 'test@user.com', otp: '123456' }
            });
            const res = makeRes();

            redis.get.mockResolvedValueOnce('123456');
            mockModel.updateOne.mockResolvedValueOnce({ matchedCount: 1 });

            await controller.verifyEmail(req, res, next);

            expect(redis.get).toHaveBeenCalledWith(expect.stringContaining('test@user.com'));
            expect(mockModel.updateOne).toHaveBeenCalledWith(
                { email: 'test@user.com' },
                { $set: { isVerified: true } }
            );
            expect(redis.del).toHaveBeenCalled();
            expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({ message: expect.any(String) })
    );
        });

        test('returns 400 for invalid OTP', async () => {
            const req = makeReq({
                body: { email: 'test@user.com', otp: 'wrong' }
            });
            const res = makeRes();

            redis.get.mockResolvedValueOnce('123456');

            await controller.verifyEmail(req, res, next);

            expect(mockModel.updateOne).not.toHaveBeenCalled();
            expect(next).toHaveBeenCalledWith(expect.any(AppError));
            expect(next.mock.calls[next.mock.calls.length - 1][0].statusCode).toBe(400);
        });
    });

    describe('login', () => {
        test('successfully logs in with valid credentials', async () => {
            const req = makeReq({
                body: { email: 'test@user.com', password: 'password123' }
            });
            const res = makeRes();

            mockModel.findOne.mockReturnValueOnce({
                select: jest.fn().mockResolvedValueOnce({
                    _id: 'user_123',
                    password: 'hashed_pw',
                    email: 'test@user.com'
                })
            });
            bcrypt.compare.mockResolvedValueOnce(true);

            await controller.login(req, res, next);

            expect(checkLockout).toHaveBeenCalledWith('project_1', 'test@user.com');
            expect(bcrypt.compare).toHaveBeenCalledWith('password123', 'hashed_pw');
            expect(clearLockout).toHaveBeenCalledWith('project_1', 'test@user.com');
            expect(issueAuthTokens).toHaveBeenCalled();
            expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({
                token: 'signed_access_token'
            })
    );
        });

        test('returns 400 for incorrect password', async () => {
            const req = makeReq({
                body: { email: 'test@user.com', password: 'wrongpassword' }
            });
            const res = makeRes();

            mockModel.findOne.mockReturnValueOnce({
                select: jest.fn().mockResolvedValueOnce({
                    _id: 'user_123',
                    password: 'hashed_pw'
                })
            });
            bcrypt.compare.mockResolvedValueOnce(false);

            await controller.login(req, res, next);

            expect(recordFailedAttempt).toHaveBeenCalledWith('project_1', 'test@user.com');
            expect(next).toHaveBeenCalledWith(expect.any(AppError));
            expect(next.mock.calls[next.mock.calls.length - 1][0].statusCode).toBe(400);
        });

        test('returns 423 when account is already locked', async () => {
            const req = makeReq({
                body: { email: 'test@user.com', password: 'password123' }
            });
            const res = makeRes();

            checkLockout.mockResolvedValueOnce({ locked: true, retryAfterSeconds: 900 });

            await controller.login(req, res, next);

            expect(bcrypt.compare).not.toHaveBeenCalled();
            expect(recordFailedAttempt).not.toHaveBeenCalled();
            expect(next).toHaveBeenCalledWith(expect.any(AppError));
            expect(next.mock.calls[next.mock.calls.length - 1][0].statusCode).toBe(423);
        });

        test('returns 423 when failures reach lockout threshold', async () => {
            const req = makeReq({
                body: { email: 'test@user.com', password: 'wrongpassword' }
            });
            const res = makeRes();

            mockModel.findOne.mockReturnValueOnce({
                select: jest.fn().mockResolvedValueOnce({
                    _id: 'user_123',
                    password: 'hashed_pw'
                })
            });
            bcrypt.compare.mockResolvedValueOnce(false);
            recordFailedAttempt.mockResolvedValueOnce({ locked: true, retryAfterSeconds: 900, attempts: 5 });

            await controller.login(req, res, next);

            expect(next).toHaveBeenCalledWith(expect.any(AppError));
            expect(next.mock.calls[next.mock.calls.length - 1][0].statusCode).toBe(423);
        });

        test('user-not-found branch records attempt and returns 423 when lockout is reached', async () => {
            const req = makeReq({
                body: { email: 'missing@user.com', password: 'wrongpassword' }
            });
            const res = makeRes();

            checkLockout.mockResolvedValueOnce({ locked: false, retryAfterSeconds: 0 });
            mockModel.findOne.mockReturnValueOnce({
                select: jest.fn().mockResolvedValueOnce(null)
            });
            recordFailedAttempt.mockResolvedValueOnce({ locked: true, retryAfterSeconds: 900, attempts: 5 });

            await controller.login(req, res, next);

            expect(recordFailedAttempt).toHaveBeenCalledWith('project_1', 'missing@user.com');
            expect(next).toHaveBeenCalledWith(expect.any(AppError));
            expect(next.mock.calls[next.mock.calls.length - 1][0].statusCode).toBe(423);
        });
    });

    describe('requestPasswordReset', () => {
        test('generates OTP and queues email', async () => {
            const req = makeReq({
                body: { email: 'reset@user.com' }
            });
            const res = makeRes();

            mockModel.findOne.mockResolvedValueOnce({ _id: 'user_123' });
            redis.get.mockResolvedValueOnce(null); // no cooldown

            await controller.requestPasswordReset(req, res, next);

            expect(redis.set).toHaveBeenCalledWith(expect.stringContaining('otp:reset:reset@user.com'), expect.any(String), 'EX', 300);
            expect(authEmailQueue.add).toHaveBeenCalledWith('send-reset-email', expect.objectContaining({
                email: 'reset@user.com'
            }));
            expect(res.json).toHaveBeenCalled();
        });

        test('returns 429 when reset OTP cooldown is active (before DB lookup)', async () => {
            const req = makeReq({ body: { email: 'reset@user.com' } });
            const res = makeRes();

            redis.get.mockResolvedValueOnce('1'); // cooldown active — checked before findOne
            redis.ttl.mockResolvedValueOnce(45);

            await controller.requestPasswordReset(req, res, next);

            expect(mockModel.findOne).not.toHaveBeenCalled(); // DB never queried
            expect(authEmailQueue.add).not.toHaveBeenCalled();
            expect(next).toHaveBeenCalledWith(expect.any(AppError));
            expect(next.mock.calls[next.mock.calls.length - 1][0].statusCode).toBe(429);
            
        });

        test('sets cooldown for unknown email to prevent account enumeration', async () => {
            const req = makeReq({ body: { email: 'unknown@user.com' } });
            const res = makeRes();

            redis.get.mockResolvedValueOnce(null); // no cooldown
            mockModel.findOne.mockResolvedValueOnce(null); // user does not exist

            await controller.requestPasswordReset(req, res, next);

            const cooldownCall = redis.set.mock.calls.find(c => c[0].includes('otp:cooldown:reset'));
            expect(cooldownCall).toBeDefined(); // cooldown set even for unknown email
            expect(authEmailQueue.add).not.toHaveBeenCalled();
            expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({ message: expect.any(String) })
    );
        });

        test('sets cooldown after sending reset OTP', async () => {
            const req = makeReq({ body: { email: 'reset@user.com' } });
            const res = makeRes();

            mockModel.findOne.mockResolvedValueOnce({ _id: 'user_123' });
            redis.get.mockResolvedValueOnce(null);

            await controller.requestPasswordReset(req, res, next);

            const cooldownCall = redis.set.mock.calls.find(c => c[0].includes('otp:cooldown:reset'));
            expect(cooldownCall).toBeDefined();
            expect(cooldownCall[2]).toBe('EX');
            expect(cooldownCall[3]).toBe(60);
        });

        test('uses normalized email in Redis key', async () => {
            const req = makeReq({ body: { email: 'Reset@User.COM' } });
            const res = makeRes();

            mockModel.findOne.mockResolvedValueOnce({ _id: 'user_123' });
            redis.get.mockResolvedValueOnce(null);

            await controller.requestPasswordReset(req, res, next);

            const otpCall = redis.set.mock.calls.find(c => c[0].includes('otp:reset'));
            expect(otpCall[0]).toContain('reset@user.com');
        });
    });

    describe('resetPasswordUser', () => {
        test('resets password with valid OTP', async () => {
            const req = makeReq({
                body: { email: 'reset@user.com', otp: '123456', newPassword: 'newpassword123' }
            });
            const res = makeRes();

            redis.get.mockResolvedValueOnce('123456');
            mockModel.updateOne.mockResolvedValueOnce({ matchedCount: 1 });

            await controller.resetPasswordUser(req, res, next);

            expect(bcrypt.hash).toHaveBeenCalledWith('newpassword123', 'salt');
            expect(mockModel.updateOne).toHaveBeenCalledWith(
                { email: 'reset@user.com' },
                { $set: { password: 'hashed_pw' } }
            );
            expect(clearLockout).toHaveBeenCalledWith('project_1', 'reset@user.com');
            expect(redis.del).toHaveBeenCalled();
            expect(res.json).toHaveBeenCalled();
        });
    });

    describe('changePasswordUser', () => {
        test('changes password if current password is correct', async () => {
            const req = makeReq({
                body: { currentPassword: 'oldpassword', newPassword: 'newpassword123' },
                headers: { 'Authorization': 'Bearer valid_token' }
            });
            const res = makeRes();

            jwt.verify.mockReturnValueOnce({ userId: 'user_123' });
            mockModel.findOne.mockResolvedValueOnce({ _id: 'user_123', password: 'old_hashed_pw' });
            bcrypt.compare.mockResolvedValueOnce(true);

            await controller.changePasswordUser(req, res, next);

            expect(bcrypt.compare).toHaveBeenCalledWith('oldpassword', 'old_hashed_pw');
            expect(bcrypt.hash).toHaveBeenCalledWith('newpassword123', 'salt');
            expect(mockModel.updateOne).toHaveBeenCalledWith(
                { _id: expect.anything() },
                { $set: { password: 'hashed_pw' } }
            );
            expect(res.json).toHaveBeenCalled();
        });

        test('returns 400 if current password is wrong', async () => {
            const req = makeReq({
                body: { currentPassword: 'wrongpassword', newPassword: 'newpassword123' },
                headers: { 'Authorization': 'Bearer valid_token' }
            });
            const res = makeRes();

            jwt.verify.mockReturnValueOnce({ userId: 'user_123' });
            mockModel.findOne.mockResolvedValueOnce({ _id: 'user_123', password: 'old_hashed_pw' });
            bcrypt.compare.mockResolvedValueOnce(false);

            await controller.changePasswordUser(req, res, next);

            expect(mockModel.updateOne).not.toHaveBeenCalled();
            expect(next).toHaveBeenCalledWith(expect.any(AppError));
            expect(next.mock.calls[next.mock.calls.length - 1][0].statusCode).toBe(400);
        });
    });
});

// =============================================================================
// Issue #181 — Redis resilience tests for checkLockout/recordFailedAttempt
// =============================================================================


describe('Login lockout — Redis resilience (Issue #181)', () => {

    beforeEach(() => {
        jest.clearAllMocks();
    });

    // ── 1. checkLockout Redis failure ──────────────────────────────────────
    describe('checkLockout rejects when Redis is down', () => {

        test('returns 503 and does not surface the raw Redis error', async () => {
            checkLockout.mockRejectedValue(new Error('Redis connection refused'));

            const req = makeReq({ body: { email: 'test@user.com', password: 'password123' } });
            const res = makeRes();

            await controller.login(req, res);

            // Controller returns 503 service error — not a 500 crash
            expect(res.status).toHaveBeenCalledWith(503);
            expect(res.status).not.toHaveBeenCalledWith(500);
        });

        test('Redis connection error is not exposed in the response body', async () => {
            checkLockout.mockRejectedValue(new Error('Redis connection refused'));

            const req = makeReq({ body: { email: 'test@user.com', password: 'password123' } });
            const res = makeRes();

            await controller.login(req, res);

            const jsonArg = res.json.mock.calls[0]?.[0];
            expect(JSON.stringify(jsonArg)).not.toMatch(/redis/i);
            expect(JSON.stringify(jsonArg)).not.toMatch(/connection refused/i);
        });

        test('response message is safe and generic', async () => {
            checkLockout.mockRejectedValue(new Error('Redis connection refused'));

            const req = makeReq({ body: { email: 'test@user.com', password: 'password123' } });
            const res = makeRes();

            await controller.login(req, res);

            const jsonArg = res.json.mock.calls[0]?.[0];
            expect(jsonArg).toHaveProperty('message', 'Login lockout service unavailable');
        });
    });

    // ── 2. recordFailedAttempt Redis failure ───────────────────────────────
    describe('recordFailedAttempt rejects when Redis is down', () => {

        test('returns 503 on wrong password when recordFailedAttempt throws — not 500', async () => {
            checkLockout.mockResolvedValue({ locked: false, retryAfterSeconds: 0 });
            recordFailedAttempt.mockRejectedValue(new Error('Redis write failed'));

            const req = makeReq({ body: { email: 'test@user.com', password: 'wrongpassword' } });
            const res = makeRes();

            mockModel.findOne.mockReturnValueOnce({
                select: jest.fn().mockResolvedValueOnce({
                    _id: 'user_123', password: 'hashed_pw', email: 'test@user.com'
                })
            });
            bcrypt.compare.mockResolvedValueOnce(false);

            await controller.login(req, res);

            expect(res.status).toHaveBeenCalledWith(503);
            expect(res.status).not.toHaveBeenCalledWith(500);
        });

        test('Redis error from recordFailedAttempt is not surfaced in the response', async () => {
            checkLockout.mockResolvedValue({ locked: false, retryAfterSeconds: 0 });
            recordFailedAttempt.mockRejectedValue(new Error('Redis write failed'));

            const req = makeReq({ body: { email: 'test@user.com', password: 'wrongpassword' } });
            const res = makeRes();

            mockModel.findOne.mockReturnValueOnce({
                select: jest.fn().mockResolvedValueOnce({
                    _id: 'user_123', password: 'hashed_pw', email: 'test@user.com'
                })
            });
            bcrypt.compare.mockResolvedValueOnce(false);

            await controller.login(req, res);

            const jsonArg = res.json.mock.calls[0]?.[0];
            expect(JSON.stringify(jsonArg)).not.toMatch(/redis/i);
            expect(JSON.stringify(jsonArg)).not.toMatch(/write failed/i);
        });
    });

    // ── 3. clearLockout Redis failure (fail-open) ──────────────────────────
    describe('clearLockout rejects when Redis is down', () => {

        test('login still succeeds and returns token even when clearLockout throws', async () => {
            checkLockout.mockResolvedValue({ locked: false, retryAfterSeconds: 0 });
            clearLockout.mockRejectedValue(new Error('Redis unavailable'));

            const req = makeReq({ body: { email: 'test@user.com', password: 'password123' } });
            const res = makeRes();

            mockModel.findOne.mockReturnValueOnce({
                select: jest.fn().mockResolvedValueOnce({
                    _id: 'user_123', password: 'hashed_pw', email: 'test@user.com'
                })
            });
            bcrypt.compare.mockResolvedValueOnce(true);

            await controller.login(req, res);

            // clearLockout is fail-open — login must still succeed
            expect(res.status).not.toHaveBeenCalledWith(500);
            expect(res.status).not.toHaveBeenCalledWith(503);
            expect(res.json).toHaveBeenCalledWith(
                expect.objectContaining({ token: 'signed_access_token' })
            );
        });

        test('Redis error from clearLockout is not exposed to the caller', async () => {
            checkLockout.mockResolvedValue({ locked: false, retryAfterSeconds: 0 });
            clearLockout.mockRejectedValue(new Error('Redis unavailable'));

            const req = makeReq({ body: { email: 'test@user.com', password: 'password123' } });
            const res = makeRes();

            mockModel.findOne.mockReturnValueOnce({
                select: jest.fn().mockResolvedValueOnce({
                    _id: 'user_123', password: 'hashed_pw', email: 'test@user.com'
                })
            });
            bcrypt.compare.mockResolvedValueOnce(true);

            await controller.login(req, res);

            const jsonArg = res.json.mock.calls[0]?.[0];
            expect(JSON.stringify(jsonArg)).not.toMatch(/redis/i);
            expect(JSON.stringify(jsonArg)).not.toMatch(/unavailable/i);
        });
    });

    // ── 4. Normal lockout behavior when Redis is healthy ───────────────────
    describe('lockout works correctly when Redis is healthy', () => {

        test('returns 423 when account is locked out', async () => {
            checkLockout.mockResolvedValue({ locked: true, retryAfterSeconds: 600 });

            const req = makeReq({ body: { email: 'test@user.com', password: 'password123' } });
            const res = makeRes();

            await controller.login(req, res);

            expect(res.status).toHaveBeenCalledWith(423);
        });

        test('returns 400 on wrong password when Redis is healthy', async () => {
            checkLockout.mockResolvedValue({ locked: false, retryAfterSeconds: 0 });
            recordFailedAttempt.mockResolvedValue({ locked: false, retryAfterSeconds: 0, attempts: 1 });

            const req = makeReq({ body: { email: 'test@user.com', password: 'wrongpassword' } });
            const res = makeRes();

            mockModel.findOne.mockReturnValueOnce({
                select: jest.fn().mockResolvedValueOnce({
                    _id: 'user_123', password: 'hashed_pw', email: 'test@user.com'
                })
            });
            bcrypt.compare.mockResolvedValueOnce(false);

            await controller.login(req, res);

            expect(res.status).toHaveBeenCalledWith(400);
        });
    });
});